### ISSUE TITLE
1.11 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [taoneill/war#837]
Hello,

Could you add please, 1.11 support to this fantastic plugin ? :D 

Thanks ! :D

**Comment by kugick** [comment]
We'll try to give it a look when we can.

**Comment by TheIntelloBox** [comment]
When do you think ? :D

**Comment by dylanhansch** [comment]
The devs all have very busy schedules. It'll need to be tested to determine what exactly needs updating. Time to update will depend on that. Best to just be patient. :)

**Comment by TheIntelloBox** [comment]
Okay. :) But please, do it fast, before January. xD

**Comment by cmastudios** [comment]
Posting the current issues that cause the plugin to not work under 1.11 will help speed development too! For example, if you install War in your 1.11 server and it produces an error message in console, post that here. If something simply doesn't work (cakes, creating war zones) post that as well.

**Comment by TheIntelloBox** [comment]
Okay. :(

**Comment by dylanhansch** [comment]
Here's an error I receive when executing /leave. @TheIntelloBox If you could provide details about the issues you're experiencing that'd be great.

```
27.11 23:03:19 [Server] INFO Petabyte issued server command: /leave
27.11 23:03:19 [Server] ERROR null
27.11 23:03:19 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'leave' in plugin War v1.9-SNAPSHOT
27.11 23:03:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
27.11 23:03:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
27.11 23:03:19 [Server] INFO Caused by: java.lang.NullPointerException: The validated object is null
27.11 23:03:19 [Server] INFO at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.NonNullList.set(SourceFile:45) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at net.minecraft.server.v1_11_R1.InventoryCraftResult.setItem(InventoryCraftResult.java:91) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:83) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.clear(CraftInventory.java:409) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.clear(CraftInventory.java:414) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO at com.tommytony.war.Warzone.preventItemHackingThroughOpenedInventory(Warzone.java:651) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.Warzone.restorePlayerState(Warzone.java:626) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.Team.removePlayer(Team.java:490) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1203) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1196) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.command.LeaveCommand.handle(LeaveCommand.java:36) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.command.WarCommandHandler.handle(WarCommandHandler.java:133) ~[?:?]
27.11 23:03:19 [Server] INFO at com.tommytony.war.War.onCommand(War.java:370) ~[?:?]
27.11 23:03:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot57.jar:git-Spigot-d60de0a-54450b7]
27.11 23:03:19 [Server] INFO ... 15 more
```

**Comment by cmastudios** [comment]
I just got around to testing this. I'm not getting the error that @dylanhansch has with /leave on Minecraft 1.11 and War 1.9 release. That error also looks like it is the responsibility of the server and may have been fixed by Spigot already. I'm not finding an issue with War on 1.11. 

What issues are everyone experiencing?
