### ISSUE TITLE
War doesn't work correctly when players have less health via item attributes

### ISSUE THREAD

**Issue by aurorasmiles** [taoneill/war#840]
When you set the max health of a player to a value less than 20, for example with item attributes, war throws an exception as soon as you are trying to leave the warzone.
```
[13:14:35 INFO]: Relaking issued server command: /leave
[13:14:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'leave' in plugin War v1.9-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1384) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 14.0, but was 20.0. (attribute base value: 20.0, player: Relaking)
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) ~[spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        at com.tommytony.war.Warzone.restorePlayerState(Warzone.java:630) ~[?:?]
        at com.tommytony.war.Team.removePlayer(Team.java:490) ~[?:?]
        at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1203) ~[?:?]
        at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1196) ~[?:?]
        at com.tommytony.war.command.LeaveCommand.handle(LeaveCommand.java:36) ~[?:?]
        at com.tommytony.war.command.WarCommandHandler.handle(WarCommandHandler.java:133) ~[?:?]
        at com.tommytony.war.War.onCommand(War.java:370) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_game_paper_1.11.2-1029.jar:git-Paper-"e3070b32"]
        ... 15 more

```

**Comment by cmastudios** [comment]
Would you be able to verify that the same error occurs on a regular installation of craftbukkit only (e.g. install craftbukkit in a new directory and copy your world files and War config)? Thanks for the report; I will look into the issue shortly.

**Comment by aurorasmiles** [comment]
Yep, just tried the same thing on a fresh installation and the same error.
```
[22:46:30 INFO]: Relaking issued server command: /leave
[22:46:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'leave' in plugin War v1.9-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1295) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1155) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 14.0(20.0)
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at com.tommytony.war.Warzone.restorePlayerState(Warzone.java:630) ~[?:?]
        at com.tommytony.war.Team.removePlayer(Team.java:490) ~[?:?]
        at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1203) ~[?:?]
        at com.tommytony.war.Warzone.handlePlayerLeave(Warzone.java:1196) ~[?:?]
        at com.tommytony.war.command.LeaveCommand.handle(LeaveCommand.java:36) ~[?:?]
        at com.tommytony.war.command.WarCommandHandler.handle(WarCommandHandler.java:133) ~[?:?]
        at com.tommytony.war.War.onCommand(War.java:370) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        ... 15 more
```

Maybe here also the give-command for the Item, in this case it's an elytra but it works with every other armor as well.
`/give Relaking elytra 1 0 {AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:-6,Operation:0,UUIDMost:45017,UUIDLeast:9177}],HideFlags:7}`

**Comment by cmastudios** [comment]
This issue should be fixed with this build: http://ftp.cmastudios.me/maven/com/tommytony/war/1.10-SNAPSHOT/war-1.10-20170716.230649-2.jar
